### ISSUE TITLE
Questions about ade-20k openset evaluation

### ISSUE THREAD

**Issue by DuowenC** [UX-Decoder/DINOv#13]
Dear authors, thanks for your great work! 

I meet a problem when evaluating on ADE20K dataset: "KeyError: "Dataset  'ade20k_panoptic_val' is not  registered! Available datasets are: coco_2014_train... ade20k_sem_seg_val...sam_val", how can i fix this problem?

**Comment by FengLi-ust** [comment]
Hi, it should have been registered here https://github.com/UX-Decoder/DINOv/blob/813f7ea681c21d95423efac46c86773bae294c3d/datasets/registration/__init__.py#L4C5-L4C29

**Comment by DuowenC** [comment]
@FengLi-ust Thanks for your quick reply! But I still meet the same error as aboves, maybe because I don't put the processed ade20k dataset to the correct data path. By default, where I should put the dataset in the folder (path) ? Thank you!
