### ISSUE TITLE
problem about sam tsv file path structure

### ISSUE THREAD

**Issue by DuowenC** [UX-Decoder/DINOv#17]
Dear authors, thanks for your wonderful work! Could you please tell me the path structure of sam tsv file? Because I meet the error: Assertion Error: Dataset **'sam_train'** is empty! (Before this, I have export sam_path, xxx, as your instructions, the process has printed 'using training file xxx files xxxx', totoal images 559300, but for the **DatasetCatalog.get('sam_train')**, it meets error as above! )

**Comment by zimoqingfeng** [comment]
I meet the same problem, how to fix it?

**Comment by zimoqingfeng** [comment]
'export SAM_DATASET' in readme.md may be corrected by ''export SAM_DATASETS'
