### ISSUE TITLE
error after run code.

### ISSUE THREAD

**Issue by geonuk-kimmm** [UX-Decoder/DINOv#25]
Thx for releasing source code.
I have trouble with running code with following your description.
When i ran `python_train_net.py `or `python demo_openset.py` , i got following error.
![image](https://github.com/UX-Decoder/DINOv/assets/34879386/e0365ed4-8fcb-47cd-a34e-6b69d8209c92)

I used CUDA 12.2 and installed torch==1.13.1, torchvision==0.14.1

**Comment by peterpanyunze** [comment]
Hitting on the same issue, could you share how you solved this?
