### ISSUE TITLE
Low AP on coco_2017_val

### ISSUE THREAD

**Issue by Artificial-Inability** [UX-Decoder/DINOv#5]
Hi, Thanks for your great work and code.
I tried to eval coco_2017_val (instances_val2017.json) using the official swint model you released yesterday but got a low bbox and segm AP. I only made some minimal changes to the conifg like changing 'coco_2017_val_panoptic_with_sem_seg' to 'coco_2017_val' and some corresponding path changes. I'm using 2gpu and set the total batch_size=2 inference_example=16, though it shouldn't influence the result. Can you try the official swint model on coco_2017_val(instances_val2017.json) and check if my results are wrong? Thanks!

![swint_bbox](https://github.com/UX-Decoder/DINOv/assets/102346323/5623374a-dc46-4e6e-b919-487b7842df02)
![swint_segm](https://github.com/UX-Decoder/DINOv/assets/102346323/18531103-5eb4-4eed-b4d1-15eeaebbf117)

**Comment by FengLi-ust** [comment]
Hi, I evaluated again and the results are correct. I think you should use `coco_2017_val_panoptic_with_sem_seg`, as we evaluate panoptic segmentation, not instance segmentation.

**Comment by Artificial-Inability** [comment]
Hi, I used panoptic_val2017.json and get similar PQ、Mask AP、Box AP as the paper stated. However, I'm still confused by the result of using instance_val2017.json.

I made an experiment that I use panoptic_val2017.json in --eval_get_content_features mode to generate prompt queries of 133 classes. Then I delete those 'stuff' classes and keep 80 'thing' classes prompt queries. And I use **instances_val2017.json** to eval in --eval_visual_openset mode and get similar Box AP、Mask AP result as the paper stated.

So I would assume the gap between Box AP(18.1 -> 45.7 in my experiments) is from the eval_get_content_features stage. To be more specific, the prompt queries of the first 80 classes is different when using panoptic_val2017.json and instances_val2017.json. However, I thought the first 80 'thing' classes mask should be same(or similar) in instance segmentation and panoptic segmentation. Could you explain why there is a big gap in Box AP ?

**Comment by Artificial-Inability** [comment]
Hi, I have figured out what happened. Detectron2 has a different loading pattern for panoptic_val2017.json and instances_val2017.json which results in a different gt order. To be more specific, if you check 'targets_per_image ' in the following code you will find that 'targets_per_image.gt_classes' is in ascending order(e.g. [0,0,24,25,25,30]) when loading panoptic_val2017.json and random order(e.g. [30,0,24,25,0,25]) when loading instances_val2017.json.
https://github.com/UX-Decoder/DINOv/blob/f5723f6f4a07d2be94145ce9d9f33b3f013d7738/dinov/architectures/dinov.py#L956-L958

Though the boxes and masks in 'targets_per_image' is in the same order of classes which is expected, you didn't handle the random order case when you save the prompt into the folders. In other words, there are many prompts which are not belonged to class X saved into the 'X' folder, which results in wrong behavior when you load prompts in the second eval_visual_openset mode.

I solved this problem by simply sorting the 'targets_per_image' above to make its gt sorted by ascending order of gt_classes, then I got the correct Box AP and Mask AP by using instances_val2017.json. You can also fix it by saving prompt to correct folder. It should be a common bug when the gt is stored in the format of instance segmentation or detection bbox.

**Comment by zzz123123123123** [comment]
你好，我在测试 panoptic_val2017.json 时，为什么PQ总是比论文低三到四个点，请问你遇到过类似问题吗，怎么解决的
